

server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect


